site_name: Documentation

theme: 
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: green
  logo: assets/itx-logo.png  

plugins:
  - search

nav:
  - Playground: playground/

extra_css:
  - style.css