site_name: Documentation

theme: 
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: green
  logo: assets/itx-logo.png  

plugins:
  - search

nav:
  - Concepts: concepts.md
  - Getting Started: getting-started.md
  - Keywords: keywords.md
  - External Sites:
    - Playground: playground/